---
title: "The 9-80 Alarm Clock"
subtitle: A practical implementation of RTOS.
order: 3

listing:
  contents: ./
  type: default
  sort: "date desc"
  categories: true

draft: true
---
<!--___________________________________________________________________|
|______________________________________________________________________|
|        _   __   _   _ _   _   _   _         _                        |
|   |   |_| | _  | | | V | | | | / |_/ |_| | /                         |
|   |__ | | |__| |_| |   | |_| | \ |   | | | \_                        |
|    _  _         _ ___  _       _ ___   _                    / /      |
|   /  | | |\ |  \   |  | / | | /   |   \                    (^^)      |
|   \_ |_| | \| _/   |  | \ |_| \_  |  _/                    (____)o   |
|______________________________________________________________________|
|______________________________________________________________________|
|                                                                      |
|----------------------------------------------------------------------|
|   Copyright 2025, Rebecca Rashkin                                    |
|   -------------------------------                                    |
|   This code may be copied, redistributed, transformed, or built      |
|   upon in any format for educational, non-commercial purposes.       |
|                                                                      |
|   Please give me appropriate credit should you choose to use this    |
|   resource. Thank you :)                                             |
|----------------------------------------------------------------------|
|                                                                      |
|______________________________________________________________________|
|   //\^.^/\\  //\^.^/\\  //\^.^/\\  //\^.^/\\  //\^.^/\\  //\^.^/\\   |
|____________________________________________________________________-->
<!--DESCRIPTION
|   This file contains configuration information for the 9-80 alarm
|   blog.
|____________________________________________________________________-->


## Motivation

I work a 9-80 schedule, meaning I work 80 hours over 9 working days and take every other Friday off. This creates a problem when setting my nightstand alarm, since I haven’t been able to find a standalone alarm clock that lets me change the alarm time based not only on the day, but also on the week.

I have decided to design and build such a device myself, not only for the utility of the end product and its direct application in my life, but also as an opportunity to put into practice RTOS development and the implementation of the [4+1 model for software architecture](https://en.wikipedia.org/wiki/4%2B1_architectural_view_model).

## Platform

I am designing this product with [QNX](/reference/qnx__ref/) due to its common use in industry and the availability of a free non-commercial license. I will be using a Raspberry Pi target and the DS323 real-time clock module that I used in [ColorClock](/projects/color-clock/).

## The Development Process

Just like ColorClock, I will be documenting my process as I learn the framework, design the software, and prototype the hardware.

[Blog](./blog__9-80-alarm/)
