#_______________________________________________________________________
#_______________________________________________________________________
#        _   __   _   _ _   _   _   _         _
#   |   |_| | _  | | | V | | | | / |_/ |_| | /
#   |__ | | |__| |_| |   | |_| | \ |   | | | \_
#    _  _         _ ___  _       _ ___   _                    / /
#   /  | | |\ |  \   |  | / | | /   |   \                    (^^)
#   \_ |_| | \| _/   |  | \ |_| \_  |  _/                    (____)o
#_______________________________________________________________________
#_______________________________________________________________________
#
#-----------------------------------------------------------------------
#   Copyright 2025, Rebecca Rashkin
#   -------------------------------
#   This code may be copied, redistributed, transformed, or built
#   upon in any format for educational, non-commercial purposes.
#
#   Please give me appropriate credit should you choose to use this
#   resource. Thank you :)
#-----------------------------------------------------------------------
#
#_______________________________________________________________________
#   //\^.^/\\  //\^.^/\\  //\^.^/\\  //\^.^/\\  //\^.^/\\  //\^.^/\\
#_______________________________________________________________________
#   DESCRIPTION
#   This file contains the configuration information for the quarto
#   project.
#_______________________________________________________________________

project:
  type        : website
  output-dir  : publish
  resources   :
    - assets/**
    - "CNAME"
    - darkmode.js

website:
  title: "Rebecca Jennifer Rashkin"
  favicon: assets/icons/rabbit-face.png
  navbar:
    right:
      - text: "Projects"
        href: projects/index.qmd

      - text: "Reference"
        href: reference/color-theme__reference/index.qmd

      - text: "Teaching"
        menu:
          - text: "How to Learn"
            href: education/how-to-learn.qmd
          - text: "Computer Systems and Assembly Course"
            href: education/comp-org/comp-org.qmd
          - text: How to View Worksheet Answers
            href: education/comp-org/worksheet-answers.qmd

      - text: "Contact"
        href: contact.qmd

    tools:
      - icon: moon
        href: "javascript:void(0)"

      - icon: linkedin
        href: https://linkedin.com/in/rebeccajr
      - icon: github
        href: https://github.com/rebeccajennifer
      - icon: instagram
        href: https://www.instagram.com/anonymous_rabbit/

  page-footer:
    center: "©2025 Rebecca Jennifer Rashkin"
    left  : rebeccarashkin (at) gmail (dot) com
    right :
      - icon: linkedin
        href: https://linkedin.com/in/rebeccajr
      - icon: github
        href: https://github.com/rebeccajennifer
      - icon: instagram
        href: https://www.instagram.com/anonymous_rabbit/

  sidebar:
    - id: comp-org
      contents: education/comp-org/

    - id: projects
      href: projects/index.qmd
      contents: projects/
      contents-depth: 1

    - id: color-clock-blog-sidebar
      contents: projects/color-clock/blog__color-clock/

    - id: reference
      contents: reference/


format:
  html:
    css       : flux-bunny.css
    code-fold : true
    toc-title : "Table of Contents"
    include-after-body: assets/ui-elements/footer.html

    toc: true
    toc-depth: 0