<!--___________________________________________________________________|
|______________________________________________________________________|
|        _   __   _   _ _   _   _   _         _                        |
|   |   |_| | _  | | | V | | | | / |_/ |_| | /                         |
|   |__ | | |__| |_| |   | |_| | \ |   | | | \_                        |
|    _  _         _ ___  _       _ ___   _                    / /      |
|   /  | | |\ |  \   |  | / | | /   |   \                    (^^)      |
|   \_ |_| | \| _/   |  | \ |_| \_  |  _/                    (____)o   |
|______________________________________________________________________|
|______________________________________________________________________|
|                                                                      |
|----------------------------------------------------------------------|
|   Copyright 2025, Rebecca Rashkin                                    |
|   -------------------------------                                    |
|   This code may be copied, redistributed, transformed, or built      |
|   upon in any format for educational, non-commercial purposes.       |
|                                                                      |
|   Please give me appropriate credit should you choose to use this    |
|   resource. Thank you :)                                             |
|----------------------------------------------------------------------|
|                                                                      |
|______________________________________________________________________|
|   //\^.^/\\  //\^.^/\\  //\^.^/\\  //\^.^/\\  //\^.^/\\  //\^.^/\\   |
|____________________________________________________________________-->
<!--DESCRIPTION
|   Sourdough recipe
|____________________________________________________________________-->

---
title: Full-Time Work Schedule Sourdough
subtitle: Weeknight sourdough is possible!
toc: true
toc-depth: 6
---

```text
Author: Rebecca
Yield:  2 loaves
```

I'm a software engineer and work 9 hour days so I have been
experimenting with process to figure out a consistent way to feasibly
bake sourdough sandwich bread within the constraints of my work
schedule.

The process here might be a little less traditional, but it works for me
and I've been getting good results for my purposes.

## General

### Notes

1. Quantities for 1 loaf are in parentheses `()`.
2. For a variation, replace salt with `0.75 c (6 Tbsp)` of 'everything
   bagel' seasoning.
   - I use the Kirkland brand which contains `65 mg` sodium per `1/4 tsp`
   seasoning.

### Software

Qty | Ingredient
-|-
`250 g  (125 g)`  | Happy starter
`700 g  (350 g)`  | Filtered water
`1000 g (500 g)`  | All purpose or bread flour
`24 g   (12 g)`   | Salt*
`~ 2 qt`          | Boiling water

\* Substitute with `0.75 c (6 Tbsp)` everything bagel seasoning for
a tasty variation.

### Hardware

Qty | Equipment
-|-
`1`     | Oven
`1`     | Kitchen scale
`1`     | Probe thermometer
`2 or 4 (1 or 2)`* | Loaf pans
`2 (1)` | (Optional) Parchment paper sheet for lining loaf pan
`1`     | Mixing bowl
`2 (1)` | Containers with lids for dough refrigeration (e.g. mixing bowl, pot with lid, etc)
`1`     | Silicone coated flipper
`1`     | Rimmed baking sheet or any other pan with sides (to hold water for baking)
`1`     | Kettle or device to boil 2 qt water
`2 (1)` | (Optional) Sheet of foil

\* If using the double-pan method, you will need two pans per loaf so one can serve as a lid.

#### `#ifndef STAND_MIXER` If Not Using Stand Mixer

- Dough scraper
- Surface for kneading

#### `#ifdef STAND_MIXER` If Using Stand Mixer

- Paddle attachment
- Dough hook attachment

## Process

### Day 1

#### Morning 1

1. Feed starter one last time to make enough starter for recipe
   (e.g. `100 g` happy starter + `80 g` water + `80 g` for 2 loaves).
   Some know this as leaven.

#### Evening 1

1. Mix starter + water well.

   `#ifdef STAND_MIXER` __If Using Stand Mixer__
   - Use the paddle attachment.

1. Add flour and mix until it turns to a blob. __Note:__ Do not add salt at this time. See resource on autolyse.

   `#ifdef STAND_MIXER` __If Using Stand Mixer__
   - Remove attachment after it turns into a blob.

1. Cover bowl and let it sit for 1 - 2 hr (autolyse step).

1. Mix in salt (or everything bagel seasoning for variation)
   and knead 5 - 15 min.

   `#ifndef STAND_MIXER` __If Not Using Stand Mixer__
   - Wet your hands and knead for 5 minutes or as long as you can stand.
   - Use the dough scraper to scrape up bits if they get stuck on the
   - To avoid a tough loaf, do not flour your work surface. This prevents working too much extra flour into the dough.
     surface.

   `#ifdef STAND_MIXER` __If Using Stand Mixer__
   - Use the dough hook attachment.

1. Repeat `3x`.
   1. Cover bowl for 30 minutes.
   1. 'Stretch and Fold'. See [note](#stretch-and-fold-in-mixing-bowl).

      `#ifdef STAND_MIXER` __Optional to simplify process__
      1. If using a stand mixer, you can 'stretch and fold' by leaving the dough in the mixer and just knead it with the dough hook for 30-60 seconds.

      `#else` __Or__
      1. Using the rubber flipper, scoop up dough from side of the bowl
         and fold it into the center.
      1. Turn the bowl 90 degrees and repeat for 2 - 3 full rotations.

1. Split dough in half (for two loaves), and put each dough ball into a
   container for overnight refrigeration. __Note:__ If making 2 loaves,
   you can also split the dough after refrigeration.

1. Refrigerate overnight.

### Day 2

#### Morning 2

1. Remove dough from refrigerator.
1. (Optional) Line each loaf pan with parchment paper.
1. For each dough ball:
   1. Shape by stretching and folding dough into itself until you have a smooth oblong sphere.
   1. Place smoothed dough ball into loaf pan.

   __Note:__ I shape the dough in my hands without using a surface to minimize cleanup.

1. Put loaf pans into cold oven.
1. Go to work or get on with your day.

#### Evening 2

1. After 8 - 12 hours, remove loaf pans from oven.
1. Score loaves with sharp knife.

   __Notes:__
   -  With this method, the dough might have formed a skin.
     Ensure that you break through this skin when scoring.
   - I use an X-ACTO knife to score; you can also use a lame

1. Put one oven rack on the bottom part of the oven, and one rack in the
   middle.
1. __If _not_ using double pan method:__ Put baking sheet on the bottom rack.
1. Preheat oven to 400 degrees Farenheight.
1. __If _not_ using double pan method:__
   1. Boil `2 qt` water.
   2. When oven is preheated, fill baking sheet with water
   (don't let it overflow).
1. __If using double pan method:__ To create a steam chamber, stack one pan upside-down over each loaf. Place the pans on the middle rack for an even bake.
1. __If _not_ using double pan method:__ If after 20 minutes, if the crust is already brown, cover each loaf
   with foil.
1. __If using double pan method:__ Remove top pan after 45 minutes.
1. Bake for another 5-10 minutes or until the interal temperature of bread is
   205 - 210 degrees Farenheight.
1. Remove each bread loaf from oven and pan.
1. Let it cool (or don't 😅) and cut it in half to view the beautiful
   crumb.

## Notes On My Process

### No Special Equipment

In the interest of workflow optimization, I choose to skip specialized equipment like Dutch ovens, bannetons, and flour towels. I prefer a streamlined process that minimizes maintenance and cleanup.

#### Loaf Pans

I like the having uniformly sized slices, so I prefer to bake my bread using loaf pans.

#### No Dutch Oven

To simplify my process, I replaced my Dutch oven with a double-pan method. I previously placed my loaf pans inside a Dutch oven, but the dough would often rise into the lid and scorch. Stacking two loaf pans creates the necessary steam while providing enough overhead space for the bread to grow.

#### No Flour Towels

In a household with pets, I prefer using plates or lids rather than cloth to cover my dough. This ensures a clean environment and provides a reliable seal for the refrigerator.

#### No Banneton Baskets

To streamline my workflow and cleanup, I keep my setup simple and skip the bannetons. It’s one less piece of equipment to maintain.

### Methodology

#### 'Stretch and Fold' in Mixing Bowl

To further simplify the process, I now use a stand mixer for 60 seconds instead of manual folding. Stretching and folding in the bowl with a spatula or using the traditional hand method works just as well.

#### Cold Filtered Water

While I once meticulously heated my water, I find cold filtered water works just as well. Just ensure it is filtered; chlorine in tap water can hinder your starter’s development.

### Starter Maintenance

I try to maintain a minimal amount of starter, and reduce the amount of
discard I collect.

#### Restarting After A Loaf

When making a loaf of bread and I transfer the starter to the main
mixing bowl, I save the bowl with the starter reminants and:

1. Scrape the reminants of the starter from the sides of the bowl.
1. Mix the starter reminants with equal parts water and flour
   (about `5 - 10 g`).
1. Transfer to a clean jar and put back in the fridge.

#### Reactivating Starter

I first scale up my small starter into a full-sized batch. After it doubles in volume, it’s ready to be used for the bread prep.

## Resources

[What is an autolyse?](https://www.kingarthurbaking.com/blog/2017/09/29/autolyse-sourdough#what-is)
